### PR TITLE
Correct two typos in snakemake.md

### PR DESCRIPTION
**Pull request by BjoernLudwig**
Just some minor corrections of typing errors. Thanks for the great work!

### CODE REVIEW

**Review by joergfunger — APPROVED** [review]

**Comment by BjoernLudwig** [comment]
Thanks for the approval @joergfunger ! I am wondering, if there is anything I can do for the _build_ job that is expected to run but does not yet.

**Comment by joergfunger** [comment]
I'm supposed to be able to approve the action, but not sure where. This is supposed to be here according to the [documentation ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository), though there is no option available. I'll look into that, if you have an immediate idea, let me know.

**Comment by BjoernLudwig** [comment]
I guess the workflow is not run, because this contribution is made in a public fork due to the [repository settings as described in the page linked above](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories). The [solution should be described in this part of the official docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), as far as I can see. But to be honest, I have not dealt with GitHub actions and these settings myself yet.
Anyway, there is no urgency in these changes obviously.

**Comment by joergfunger** [comment]
I've found a way around that, so thanks for the corrections. Btw, the repo is quite outdated, there is newer information related to these workflow systems available [here](https://github.com/BAMresearch/NFDI4IngScientificWorkflowRequirements).

**Pull request merged**
